INSERT INTO `edusystem`.`course`(`cid`, `cname`, `tid`, `info`, `ctime`) VALUES ('21001', '1', 21, '1', '周三');
INSERT INTO `edusystem`.`course`(`cid`, `cname`, `tid`, `info`, `ctime`) VALUES ('21002', '2', 21, '2', '周二');
INSERT INTO `edusystem`.`course`(`cid`, `cname`, `tid`, `info`, `ctime`) VALUES ('21003', '3', 21, '3', '周六');
INSERT INTO `edusystem`.`course`(`cid`, `cname`, `tid`, `info`, `ctime`) VALUES ('21004', '4', 21, '4', '周五');
INSERT INTO `edusystem`.`course`(`cid`, `cname`, `tid`, `info`, `ctime`) VALUES ('21005', '5', 21, '5', '周四');
INSERT INTO `edusystem`.`course`(`cid`, `cname`, `tid`, `info`, `ctime`) VALUES ('22001', '1', 22, '1', '周日');
INSERT INTO `edusystem`.`course`(`cid`, `cname`, `tid`, `info`, `ctime`) VALUES ('22002', '2', 22, '2', '周六');
INSERT INTO `edusystem`.`course`(`cid`, `cname`, `tid`, `info`, `ctime`) VALUES ('22003', '3', 22, '3', '周三');
INSERT INTO `edusystem`.`course`(`cid`, `cname`, `tid`, `info`, `ctime`) VALUES ('22004', '4', 22, '4', '周一');
INSERT INTO `edusystem`.`course`(`cid`, `cname`, `tid`, `info`, `ctime`) VALUES ('22005', '5', 22, '5', '周四');
INSERT INTO `edusystem`.`course`(`cid`, `cname`, `tid`, `info`, `ctime`) VALUES ('23001', '1', 23, '1', '周日');
INSERT INTO `edusystem`.`course`(`cid`, `cname`, `tid`, `info`, `ctime`) VALUES ('23002', '2', 23, '2', '周日');
INSERT INTO `edusystem`.`course`(`cid`, `cname`, `tid`, `info`, `ctime`) VALUES ('23003', '3', 23, '3', '周日');
INSERT INTO `edusystem`.`course`(`cid`, `cname`, `tid`, `info`, `ctime`) VALUES ('23004', '4', 23, '4', '周一');
INSERT INTO `edusystem`.`course`(`cid`, `cname`, `tid`, `info`, `ctime`) VALUES ('23005', '5', 23, '5', '周六');
INSERT INTO `edusystem`.`course`(`cid`, `cname`, `tid`, `info`, `ctime`) VALUES ('24001', '1', 24, '1', '周四');
INSERT INTO `edusystem`.`course`(`cid`, `cname`, `tid`, `info`, `ctime`) VALUES ('24002', '2', 24, '2', '周三');
INSERT INTO `edusystem`.`course`(`cid`, `cname`, `tid`, `info`, `ctime`) VALUES ('24003', '3', 24, '3', '周日');
INSERT INTO `edusystem`.`course`(`cid`, `cname`, `tid`, `info`, `ctime`) VALUES ('24004', '4', 24, '4', '周三');
INSERT INTO `edusystem`.`course`(`cid`, `cname`, `tid`, `info`, `ctime`) VALUES ('24005', '5', 24, '5', '周二');
INSERT INTO `edusystem`.`course`(`cid`, `cname`, `tid`, `info`, `ctime`) VALUES ('25001', '1', 25, '1', '周二');
INSERT INTO `edusystem`.`course`(`cid`, `cname`, `tid`, `info`, `ctime`) VALUES ('25002', '2', 25, '2', '周六');
INSERT INTO `edusystem`.`course`(`cid`, `cname`, `tid`, `info`, `ctime`) VALUES ('25003', '3', 25, '3', '周四');
INSERT INTO `edusystem`.`course`(`cid`, `cname`, `tid`, `info`, `ctime`) VALUES ('25004', '4', 25, '4', '周日');
INSERT INTO `edusystem`.`course`(`cid`, `cname`, `tid`, `info`, `ctime`) VALUES ('25005', '5', 25, '5', '周日');
INSERT INTO `edusystem`.`course`(`cid`, `cname`, `tid`, `info`, `ctime`) VALUES ('26001', '1', 26, '1', '周一');
INSERT INTO `edusystem`.`course`(`cid`, `cname`, `tid`, `info`, `ctime`) VALUES ('26002', '2', 26, '2', '周三');
INSERT INTO `edusystem`.`course`(`cid`, `cname`, `tid`, `info`, `ctime`) VALUES ('26003', '3', 26, '3', '周三');
INSERT INTO `edusystem`.`course`(`cid`, `cname`, `tid`, `info`, `ctime`) VALUES ('26004', '4', 26, '4', '周三');
INSERT INTO `edusystem`.`course`(`cid`, `cname`, `tid`, `info`, `ctime`) VALUES ('26005', '5', 26, '5', '周日');
INSERT INTO `edusystem`.`course`(`cid`, `cname`, `tid`, `info`, `ctime`) VALUES ('27001', '1', 27, '1', '周六');
INSERT INTO `edusystem`.`course`(`cid`, `cname`, `tid`, `info`, `ctime`) VALUES ('27002', '2', 27, '2', '周二');
INSERT INTO `edusystem`.`course`(`cid`, `cname`, `tid`, `info`, `ctime`) VALUES ('27003', '3', 27, '3', '周四');
INSERT INTO `edusystem`.`course`(`cid`, `cname`, `tid`, `info`, `ctime`) VALUES ('27004', '4', 27, '4', '周一');
INSERT INTO `edusystem`.`course`(`cid`, `cname`, `tid`, `info`, `ctime`) VALUES ('27005', '5', 27, '5', '周四');
INSERT INTO `edusystem`.`course`(`cid`, `cname`, `tid`, `info`, `ctime`) VALUES ('28001', '1', 28, '1', '周日');
INSERT INTO `edusystem`.`course`(`cid`, `cname`, `tid`, `info`, `ctime`) VALUES ('28002', '2', 28, '2', '周日');
INSERT INTO `edusystem`.`course`(`cid`, `cname`, `tid`, `info`, `ctime`) VALUES ('28003', '3', 28, '3', '周三');
INSERT INTO `edusystem`.`course`(`cid`, `cname`, `tid`, `info`, `ctime`) VALUES ('28004', '4', 28, '4', '周二');
INSERT INTO `edusystem`.`course`(`cid`, `cname`, `tid`, `info`, `ctime`) VALUES ('28005', '5', 28, '5', '周三');
INSERT INTO `edusystem`.`course`(`cid`, `cname`, `tid`, `info`, `ctime`) VALUES ('29001', '1', 29, '1', '周日');
INSERT INTO `edusystem`.`course`(`cid`, `cname`, `tid`, `info`, `ctime`) VALUES ('29002', '2', 29, '2', '周日');
INSERT INTO `edusystem`.`course`(`cid`, `cname`, `tid`, `info`, `ctime`) VALUES ('29003', '3', 29, '3', '周二');
INSERT INTO `edusystem`.`course`(`cid`, `cname`, `tid`, `info`, `ctime`) VALUES ('29004', '4', 29, '4', '周二');
INSERT INTO `edusystem`.`course`(`cid`, `cname`, `tid`, `info`, `ctime`) VALUES ('29005', '5', 29, '5', '周四');
INSERT INTO `edusystem`.`course`(`cid`, `cname`, `tid`, `info`, `ctime`) VALUES ('30001', '1', 30, '1', '周三');
INSERT INTO `edusystem`.`course`(`cid`, `cname`, `tid`, `info`, `ctime`) VALUES ('30002', '2', 30, '2', '周五');
INSERT INTO `edusystem`.`course`(`cid`, `cname`, `tid`, `info`, `ctime`) VALUES ('30003', '3', 30, '3', '周一');
INSERT INTO `edusystem`.`course`(`cid`, `cname`, `tid`, `info`, `ctime`) VALUES ('30004', '4', 30, '4', '周三');
INSERT INTO `edusystem`.`course`(`cid`, `cname`, `tid`, `info`, `ctime`) VALUES ('30005', '5', 30, '5', '周四');
INSERT INTO `edusystem`.`student_course`(`sid`, `cid`) VALUES (31, '25002');
INSERT INTO `edusystem`.`student_course`(`sid`, `cid`) VALUES (32, '29005');
INSERT INTO `edusystem`.`student_course`(`sid`, `cid`) VALUES (33, '22005');
INSERT INTO `edusystem`.`student_course`(`sid`, `cid`) VALUES (34, '24002');
INSERT INTO `edusystem`.`student_course`(`sid`, `cid`) VALUES (35, '29001');
INSERT INTO `edusystem`.`student_course`(`sid`, `cid`) VALUES (36, '24002');
INSERT INTO `edusystem`.`student_course`(`sid`, `cid`) VALUES (37, '27002');
INSERT INTO `edusystem`.`student_course`(`sid`, `cid`) VALUES (38, '22002');
INSERT INTO `edusystem`.`student_course`(`sid`, `cid`) VALUES (39, '27003');
INSERT INTO `edusystem`.`student_course`(`sid`, `cid`) VALUES (40, '26005');
